# Generated by Django 3.0.5 on 2020-04-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField(blank=True, null=True)),
                ('data_finish', models.DateField(blank=True, null=True)),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='our_calendars', to='people.People')),
            ],
        ),
    ]
